name: Fetch Swahili Podcast Episodes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # kör var 6:e timme

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Fetch Swahili podcast
        run: python website/scripts/fetch_podcast_sw.py

      - name: Generate sitemap
        run: python website/scripts/generate_sitemap.py

      - name: Commit sitemap and episodes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sw/pod/*.html seo/sitemap.xml
          git commit -m "Update Swahili podcast episodes + sitemap" || echo "No changes"
          git push
