name: Generate Sitemap

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"   # kör varje morgon 07:00 UTC

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate sitemap
        run: python scripts/generate_sitemap.py

      - name: Commit sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add seo/sitemap.xml
          git commit -m "Update sitemap" || echo "No changes"
          git push
